export const aboutData = [
    {
        title: "Enhance Yield",
        data: "Access sustainable returns generated by cash flows of real-world assets."
    },
    {
        title: "Diversify Risk",
        data: "We provide low sensitivity to equity and crypto markets by utilizing alternative investing."
    },
    {
        title: "Scalable Ecosystem",
        data: "Via the Credix platform, you can access investments via our lending marketplace, a digital-first platform."
    },
]